### ISSUE TITLE
HeroImage: remanier le format

### ISSUE THREAD

**Issue by McFlyPartages** [McFlyPartages/mcflypartages.github.io#1]
```yaml
heroImage:
  url:
  Author:
  urlAuthor:
```

Permets de citer la source lorsque j'utilise une image externe
